# Generated by Django 4.1.7 on 2023-03-08 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=200)),
                ('task_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
