# Generated by Django 4.2 on 2023-04-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0007_alter_task_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_completed',
            new_name='date_reached',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_priority',
        ),
    ]
